/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EditorIndexImport } from './routes/editor/index'
import { Route as CardsIndexImport } from './routes/cards/index'

// Create/Update Routes

const EditorIndexRoute = EditorIndexImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRoute,
} as any)

const CardsIndexRoute = CardsIndexImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsIndexImport
      parentRoute: typeof rootRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/cards': typeof CardsIndexRoute
  '/editor': typeof EditorIndexRoute
}

export interface FileRoutesByTo {
  '/cards': typeof CardsIndexRoute
  '/editor': typeof EditorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/cards/': typeof CardsIndexRoute
  '/editor/': typeof EditorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cards' | '/editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/cards' | '/editor'
  id: '__root__' | '/cards/' | '/editor/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CardsIndexRoute: typeof CardsIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  CardsIndexRoute: CardsIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/cards/",
        "/editor/"
      ]
    },
    "/cards/": {
      "filePath": "cards/index.tsx"
    },
    "/editor/": {
      "filePath": "editor/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
